services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    environment:
      - 'ENABLE_OPENAI_API=True'
      - 'ENABLE_OLLAMA_API=False'
      - 'OPENAI_API_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
volumes:
  ollama: {}
  open-webui: {}